### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by gongxxuan** [nicholasly/HDP-Net#1]
请问您提供的数据集为什么haze-free和nighthaze-1的数据一样，都是有雾图？

**Comment by nicholasly** [comment]
十分抱歉，之前上传网盘的时候我把数据弄混了，我会尽快把haze-free图片重新上传。

**Comment by nicholasly** [comment]
同学您好，这个数据集上传需要到十月份才能进行，我不确定您是否急需这个数据集。请问方便加我微信吗，您可以将您的微信号发我邮箱，我会在微信中向您说下详细情况，谢谢！

**Comment by gongxxuan** [comment]
微信号我发您邮箱了

**Comment by nicholasly** [comment]
同学，麻烦您再确认一下是否发了我主页的邮箱，我把我所有的邮箱都找了，没找到您的邮件。
